[package]
name = "enums"
version = "0.1.0"
authors = ["John C. Burnham <jcb@johnchandlerburnham.com>"]
edition = "2018"

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "main2"
path = "src/main2.rs"

[[bin]]
name = "main3"
path = "src/main3.rs"

[dependencies]
